---
title: "Indigenous areas"
author: "Mirza Cengic"
date: "September 13, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(Rahat, raster, ggnewscale, tidyverse, extdplyr, lubridate, ggmap,  ggthemes, sf,  mapview, ggsci,ggthemes, janitor, tictoc, fasterize, patchwork, glue, cowplot, ggsflabel)
```


# Load data

```{r}

rdata_path <- "Data_raw/IAA.RData"

if (!file.exists(rdata_path))
{
# Protected areas
wdpa_amazon <- st_read("Data_raw/WDPA/wdpa_amazon2.gpkg")


pa_non_ind <- wdpa_amazon %>% 
  filter(DESIG_ENG != "Indigenous Area")

# Indigenous areas
indigenous_areas <- st_read("Data/Indigenous_territories.gpkg")

# Amazon biome limits
amazon_biome <- st_read("Data_raw/amapoly_ivb/amapoly_ivb.shp")
#
viirs_filename <- "Data/VIIRS_historical_new.gpkg"

if (!file.exists(viirs_filename))
{
  historical_viirs <- st_read("Data/VIIRS_historical.gpkg")

# Load VIIRS data for 2019
viirs_2019_raw <- "Data_raw/VIIRS/DL_FIRE_V1_72707/fire_archive_V1_72707.csv" %>%   data.table::fread()

# Load last two months for VIIRS
viirs_2019_nrt_raw <- "Data_raw/VIIRS/DL_FIRE_V1_72707/fire_nrt_V1_72707.csv" %>%   data.table::fread()


viirs_2019_raw_sf <- viirs_2019_raw %>% 
  filter(confidence == "h") %>% 
  mutate(
    acq_date = as_date(acq_date)
  ) %>% 
  as_tibble() %>% 
st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  dplyr::select(acq_date)

viirs_2019_nrt_raw_sf <- viirs_2019_nrt_raw %>% 
  filter(confidence == "h") %>% 
  mutate(
    acq_date = as_date(acq_date)
  ) %>% 
  as_tibble() %>% 
st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  dplyr::select(acq_date)

#######

crop_ext <- st_bbox(amazon_biome) + c(-4, -10, 10, 5)


viirs_2019 <- rbind(viirs_2019_raw_sf, viirs_2019_nrt_raw_sf) %>% 
  st_crop(crop_ext)

# xlim = c(-79, -41), ylim = c(-20, 10)

historical_viirs_no19 <- historical_viirs %>% 
  mutate(
    acq_date = as_date(acq_date)
  ) %>% 
  filter(acq_date < "2019-01-01") %>% 
  dplyr::select(acq_date) %>% 
  st_crop(crop_ext)


viirs_data <- rbind(historical_viirs_no19, rename(viirs_2019, geom = geometry))
# plot(viirs_data[1])

st_write(viirs_data, viirs_filename)
} else {
  viirs_data <- st_read(viirs_filename)
}
#### Intersect with indigenous areas, amazon biome range, and protected areas

# fires_viirs_cleaned_filename <- "Data/fires_viirs_cleaned_amazon.gpkg"
fires_viirs_cleaned_filename <- "Data/fires_viirs_amazon.rds"
if (!file.exists(fires_viirs_cleaned_filename))
{


mydat <- read_csv("Data_raw/VIIRS/DL_FIRE_V1_79880/fire_nrt_V1_79880.csv")


mysf <- mydat %>% 
  filter(confidence == "h") %>% 
  filter(daynight == "D") %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% 
  filter(acq_date > "2019-08-31") %>% 
  dplyr::select(acq_date) %>% 
  rename(geom=geometry)


viirs_data <- viirs_data %>% 
    filter(acq_date < "2019-09-01") %>% 
  rbind(mysf)


fires_viirs_cleaned_df_raw <- viirs_data %>% 
  st_join(indigenous_areas %>% mutate(area = units::set_units(st_area(.), "km^2")), join = st_intersects) %>% mutate(
    is_ind = ifelse(is.na(id), FALSE, TRUE)) %>% 
  st_join(amazon_biome, join = st_intersects) %>% mutate(
    is_amazon = ifelse(is.na(ID), FALSE, TRUE)) %>% 
  st_join(pa_non_ind %>% mutate(area = units::set_units(st_area(.), "km^2")), join = st_intersects)



fires_viirs_cleaned_df <- fires_viirs_cleaned_df_raw %>% 
  transmute(
    acq_date,
    is_ind,
    is_amazon,
    is_pa = if_else(is.na(WDPAID), FALSE, TRUE),
        period = str_c(month(acq_date), "_", year(acq_date)),
    is_both = if_else(is_pa & is_ind, TRUE, FALSE)
  ) 

fires_viirs_cleaned_df <- fires_viirs_cleaned_df %>% 
  filter(is_amazon == TRUE)



# 
write_rds(fires_viirs_cleaned_df, fires_viirs_cleaned_filename)
# %>% 
  # st_write(fires_viirs_cleaned_filename)  

} else {
  fires_viirs_cleaned_df <- read_rds(fires_viirs_cleaned_filename)
  # fires_viirs_cleaned_df <- st_read(fires_viirs_cleaned_filename)
}

fires_viirs_cleaned <- fires_viirs_cleaned_df_raw

################################################################################
# Calculate number of events per month
fires_pa_ind <- fires_viirs_cleaned %>% 
  mutate(
    acq_date,
    is_ind,
    is_amazon,
    is_pa = if_else(is.na(WDPAID), FALSE, TRUE),
        period = str_c(month(acq_date), "_", year(acq_date)),
    is_both = if_else(is_pa & is_ind, TRUE, FALSE)
  ) %>% 
   group_by(
    period
  ) %>% 
  mutate(
    n = n(),
    is_ind_n = sum(is_ind),
    is_pa_n = sum(is_pa),
    is_both_n = sum(is_both), 
    isnt_n_grp =  n - (is_pa_n + is_ind_n)
  ) %>% 
  ungroup() %>% 
  distinct(period, .keep_all = TRUE) %>% 
  st_set_geometry(NULL) 
print("saving data")
# save.image(rdata_path)
} else {
  print("Loading data")
  load(rdata_path)
}
```

###########


# Calculate amount of fires in protected areas and indigenous reserves

```{r echo=FALSE}
fires_viirs_cleaned_raw_filename <- "Data/fires_viirs_raw.rds"

fires_viirs_cleaned_df_raw <- read_rds(fires_viirs_cleaned_raw_filename)

fires_viirs_cleaned <- fires_viirs_cleaned_df_raw


################################################################################
# Calculate number of events per month
fires_pa_ind <- fires_viirs_cleaned %>% 
  mutate(
    acq_date,
    is_ind,
    is_amazon,
    is_pa = if_else(is.na(WDPAID), FALSE, TRUE),
        period = str_c(month(acq_date), "_", year(acq_date)),
    is_both = if_else(is_pa & is_ind, TRUE, FALSE)
  ) %>% 
   group_by(
    period
  ) %>% 
  mutate(
    n = n(),
    is_ind_n = sum(is_ind),
    is_pa_n = sum(is_pa),
    is_both_n = sum(is_both), 
    isnt_n_grp =  n - (is_pa_n + is_ind_n)
  ) %>% 
  ungroup() %>% 
  distinct(period, .keep_all = TRUE) %>% 
  st_set_geometry(NULL) 

# fires_pa_ind %>% names
  # dplyr::select(acq_date, area)

fire_freq_plotdata <- fires_pa_ind %>% 
  gather("value", "cases", 8:ncol(.)) %>% 
  mutate(
    month = month(acq_date, label = TRUE),
    year = year(acq_date),
    value2 = case_when(
      value == "is_ind_n" ~ "Indigenous territories",
      value == "is_pa_n" ~ "Protected areas",
      value == "is_both_n" ~ "Both",
      value == "isnt_n_grp" ~ "Not protected",
      value == "isnt_pa_n" ~ "Not Protected"),
    value3 = case_when(
      is.na(is_pa) ~ " Not protected        ",
      value2 == "Indigenous territories" ~ " Indigenous territories        ",
      value2 == "Protected areas" ~ " Protected areas        ",
      value2 == "Not protected" ~ " Not protected        "),
        value3 = fct_relevel(value3, c(" Not protected        ",
                                       " Indigenous territories        ",
                                       " Protected areas        "))
    # value3 = fct_relevel(value2, c(" Not protected        ", 
    #                                # "Both",
    #                                " Protected areas        ",
    #                                " Indigenous territories        "))
    ) %>% 
  # filter(acq_date > "2017-07-01", value2 %in% c("Protected", "Other", "Indigenous")) %>%
  filter(value2 %in% c("Protected areas", "Not protected", "Indigenous territories"))

fire_freq_aug_plotdata <- fire_freq_plotdata %>%
  # filter(month == "Aug") %>%
  filter(month %in% c("Aug", "Sep")) %>% 
  mutate(
    # month = month(acq_date, label = TRUE, abbr = FALSE)
  ) %>% 
  ggplot() +
  aes(x = month, y = cases, fill = value3) +
  geom_col(position = "dodge") +
  ggtitle("Number of detected fires in the Amazon basin during August") +
  # scale_fill_tableau() +
     scale_fill_manual(values = c("grey70","#E18727FF", "#20854EFF")) +
  labs(x = NULL, y = "Number of detected fires", caption = "itsprettydata.com\nData source: VIIRS I-Band 375m Active Fire Data |  WDPA  |  landmarkmap.org") +
  facet_wrap(~ year, nrow = 1) +
  theme(
    plot.caption = element_text(color = "grey40", family = 'ubuntu'),
     plot.title = element_text(family = 'Helvetica-Narrow', 
                              color = 'grey10', 
                              # face = 'bold', 
                              size = 32, 
                              vjust = 1,
                              hjust = 0),
    axis.title.y = element_text(family = "ubuntu", size = 18, color = "grey5"),
    axis.text = element_text(family = "ubuntu", color = "grey5"),
    axis.text.x = element_text(size = 20),
    axis.ticks.x = element_blank(),
    legend.position = c(0.08, 0.9),
    legend.direction = "horizontal",
    legend.title = element_blank(),
    strip.text = element_text(size = 30, 
                              # family = "ubuntu",
                              margin = margin(t = 5, r = 0, b = 5, l = 0, unit = "pt"),
                              family = "Helvetica-Narrow"),
    panel.border = element_rect(colour = "black"),
    # strip.background = element_blank(),
    strip.background = element_rect(fill = "grey85"),
    legend.key.size = unit(1.25, "cm"),
    legend.text = element_text(size = 30, family = "AvantGarde")
  )

fire_freq_aug_plotdata

ggsave("Output/Figures/yearl_freq_augsept_viirs.png", fire_freq_aug_plotdata,
       width = 18,
       height = 10, dpi = 300)

#####
p_year_freq <- fire_freq_plotdata %>% 
  add_row(.before = TRUE) %>% 
  mutate(
    acq_date = as_date(ifelse(is.na(is_pa), "2011-12-31", as.character(acq_date))),
    cases = ifelse(is.na(is_pa), 0, cases),
    value3 = as.factor(ifelse(
      is.na(is_pa)," Not protected        ", as.character(value3))),
      # value3 == "Indigenous territories" ~ " Indigenous territories        ",
      # value3 == "Protected areas" ~ " Protected areas        ",
      # value3 == "Not protected" ~ " Not protected        "),
        value3 = fct_relevel(value3, c(" Not protected        ",
                                       " Indigenous territories        ",
                                       " Protected areas        "
                                       ))
    # acq_date = as_date(ifelse(acq_date == "2012-01-20", "2011-12-01", as.character(acq_date)))
    ) %>% 
  # head()
  filter(acq_date < "2019-10-01") %>%
  ggplot() +
  aes(x = acq_date, y = cases, group = value3, fill = value3) +
  geom_col(width = 26) +
  labs(x = NULL, y = "Number of detected fires", 
       title = "Number of detected fires in the Amazon basin",
       subtitle = "There was this, and there was this, and there was this.",
       caption = "itsprettydata.com\nData source: VIIRS I-Band 375m Active Fire Data |  WDPA  |  landmarkmap.org") +
  # scale_fill_tableau() +
  scale_fill_manual(values = c("grey70","#E18727FF", "#20854EFF")) +
    scale_x_date(date_labels = "%b %Y",
               date_breaks = "6 months",
               position = "bottom") +
  theme(
    axis.title.y = element_text(family = "ubuntu", size = 18, color = "grey5"),
    axis.text = element_text(size = 18, family = "ubuntu", color = "grey5"),
    axis.text.x = element_text(size = 16),
   plot.title = element_text(size = 32, 
                              family = "ubuntu",
                              color = "grey10",
                              face = "bold",
                              vjust = 1,
                              hjust = 0),
      plot.subtitle = element_text(family = "mono", 
                                 size = 16),
       plot.caption = element_text(color = "grey40", 
                                   family = 'ubuntu',
                                   vjust = 1, size = 12),
        # axis.text.x = element_blank(),
    # axis.ticks.x = element_blank(),
    # legend.position = "top",
    legend.position = c(0.01, 0.85),
    legend.direction = "horizontal",
    legend.title = element_blank(),
    strip.text = element_text(size = 22, family = "ubuntu"),
    strip.background = element_rect(fill = "orange"),
    legend.key.size = unit(1.25, "cm"),
    legend.text = element_text(size = 26, family = "AvantGarde", color = "grey10"),
    NULL
    ) +
  #### Arrow labels
  # August label
  annotate("text", x = as_date("2017-06-01"), y = 23000, hjust = 0,
           label = "August 2019 broke the record for\nmost fires detected in the Amazon region",
           family = "ubuntu", size = 7, color = "grey10") +
  annotate("curve", x = as_date("2018-11-01"), y = 22000,
           xend = as_date("2019-07-15"), yend = 19000, color = "grey10",
           curvature = 0.2,
           arrow = arrow(angle = 20, length = unit(4, "mm"), type = "closed")) +
  # Ind pa label
   annotate("text", x = as_date("2017-10-01"), y = 17000, hjust = 0,
           label = "Record number of fires in\nindigenous territories and\nprotected areas",
           family = "ubuntu", size = 7, color = "grey10") +
  annotate("curve", x = as_date("2018-10-01"), y = 15000,
           xend = as_date("2019-07-15"), yend = 4600, color = "#E18727FF",
           curvature = 0.2,
           arrow = arrow(angle = 20, length = unit(4, "mm"), type = "closed")) +
  annotate("curve", x = as_date("2018-10-01"), y = 15000,
           xend = as_date("2019-07-15"), yend = 3200, color = "#20854EFF",
           curvature = 0.2,
           arrow = arrow(angle = 20, length = unit(4, "mm"), type = "closed")) +
  # september label
  # Ind pa label
   annotate("text", x = as_date("2017-10-01"), y = 9000, hjust = 0,
           label = "There were even\nmore fires in\nSeptember",
           family = "ubuntu", size = 6, color = "grey10") +
  annotate("curve", x = as_date("2018-04-01"), y = 7200,
           xend = as_date("2019-08-15"), yend = 2300, color = "#E18727FF",
           curvature = 0.4,
           arrow = arrow(angle = 20, length = unit(4, "mm"), type = "closed"))

# "#E18727FF", "#20854EFF"
p_year_freq

ggsave(
  # "Output/Figures/yearl_freq_viirs.png",
    "/home/mirza/Projects/prettydata/content/post/03_amazon/yearl_freq_viirs.png",
  p_year_freq,
       width = 18,
       height = 10, dpi = 300)

```

# Plot indigenous areas and protected areas within amazon basin
```{r eval=FALSE, include=FALSE}

# ggplot() +
#   geom_sf(data = amazon_biome, fill = NA, color = "black") +
#   geom_sf(data = indigenous_areas, fill = "red") +
#   geom_sf(data = pa_non_ind, fill = "orange") +
#   theme_map() +
#   coord_sf()

```

# Calculate top n areas by the number of fires or by the density of fires in August

```{r}

# Calculate density of fires in indigenous areas, and get top5 by density

# See 
# fires_viirs_cleaned_df
fires_ind_august <- fires_viirs_cleaned_df %>% 
  filter(is_ind == TRUE) %>% 
    filter(is_amazon == TRUE) %>%
  mutate(
    period = str_c(month(acq_date), "_", year(acq_date))
  ) %>% 
  filter(period == "8_2019")

# Get names of top 10 indigenous terrotires with number of fires
burned_ind_areas <- fires_ind_august %>% 
  transmute(
    area = area.x,
    period,
    country, 
    category, 
    ethnic,
    name = as.character(name)
  ) %>% 
  group_by(name) %>%  
  mutate(
    fires_n = n(),
    fires_density = fires_n / area
  ) %>% 
  ungroup() %>% 
  distinct(name, .keep_all = TRUE) %>% 
  filter(country == "Brasil") %>% 
  filter(fires_n > 10) %>% 
  st_set_geometry(NULL) %>% 
  arrange(desc(fires_n)) %>% 
  mutate(
    order_n = 1:nrow(.)) %>% 
  arrange(desc(fires_density)) %>% 
  mutate(
    order_density = 1:nrow(.)
  )

top_10_ind_terr <- burned_ind_areas %>%
  slice(1:10) %>% 
  pull(name) 
  
# top_10_ind_terr %>% 
#   head(2) %>% 
#   pull(area)
top_10_ind_terr_dens <- top_10_ind_terr  


# indigenous_areas %>% 
#   filter(name %in% top_10_ind_terr) %>% 
#   mapview()
#################################

# Calculate density of fires in protected areas, and get top5 by density

# See 
# fires_viirs_cleaned_df
fires_pa_august <- fires_viirs_cleaned_df %>% 
      mutate(
        is_pa = if_else(is.na(WDPAID), FALSE, TRUE)
) %>% 
  filter(is_pa == TRUE) %>% 
    filter(is_amazon == TRUE) %>%
  mutate(
    period = str_c(month(acq_date), "_", year(acq_date))
  ) %>% 
  filter(period == "8_2019")

# Get names of top 10 pa with number of fires
burned_pa_areas <-
  fires_pa_august %>% 
  transmute(
    area = area.y,
    period,
    ISO3, 
    name = as.character(NAME)
  ) %>% 
  group_by(name) %>%  
  mutate(
    fires_n = n(),
    fires_density = fires_n / area
  ) %>% 
  ungroup() %>% 
  distinct(name, .keep_all = TRUE) %>% 
  filter(ISO3 == "BRA") %>% 
  filter(fires_n > 10) %>% 
  st_set_geometry(NULL) %>% 
  arrange(desc(fires_n)) %>% 
  mutate(
    order_n = 1:nrow(.)) %>% 
  arrange(desc(fires_density)) %>% 
  mutate(
    order_density = 1:nrow(.)
  )


############
```

# Make barchart
```{r}

# rm(fires_viirs_cleaned_df)
#### Plot stuff

p_10ind <- burned_ind_areas %>% 
  mutate(
    name = fct_reorder(name, -order_density) 
  ) %>% 
  head(10) %>% 
  ggplot() +
  aes(x = name, y = fires_density) +
  geom_col(fill = "#E18727FF") +
  coord_flip() +
  scale_y_continuous(position = "right", limits = c(0, 0.208)) +
  scale_x_discrete(position = "top") +
  labs(
    # title = "Highest density of fires during August 2019",
    title = "Top 10 areas with the highest density of fires during August 2019",
    # subtitle = "Top 10 Indigenous territories and Protected areas",
    x = NULL, y = "Density of detected fires"
    ) +
  # theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text( 
                              family = "ubuntu",
                              color = "grey10",
                              face = "bold",
                              size = 36,
                              vjust = 1,
                              hjust = 0),
    plot.subtitle = element_text(family = 'mono', 
                              color = 'grey30', 
                              # face = 'bold',
                              size = 22, 
                              vjust = 1,
                              hjust = 0),
    axis.text.y = element_text(size = 24, family = "ubuntu", color = "grey10"),
    axis.text.x = element_text(size = 18, family = "ubuntu", color = "grey20"),
    axis.title.x = element_blank(),
    axis.ticks.y = element_line(size = 2)
    # axis.title.x = element_text(family = "ubuntu", color = "grey20")
  ) +
  NULL
p_10ind
# unique(burned_pa_areas$name)
p_10pa <- burned_pa_areas %>% 
  mutate(
    
    
    name = case_when(
      name == "Floresta Estadual De Rendimento Sustentado Do Rio Madeira \"B\"" ~ "Floresta Estadual De Rendimento\nSustentado Do Rio Madeira \"B\"",
        # name == "Floresta Estadual De Rendimento Sustentado Mutum" ~ "Floresta Estadual De Rendimento\nSustentado Mutum",
        # name == "Área De Proteção Ambiental Triunfo Do Xingu"  ~ "Área De Proteção Ambiental\nTriunfo Do Xingu" ,
      # name == "Reserva Biológica Nascentes Serra Do Cachimbo" ~
      #   "Reserva Biológica Nascentes\nSerra Do Cachimbo",
      TRUE ~ name
    # 
    ),
            name = fct_reorder(name, order_density), 
            fires_n, 
            fires_density
    ) %>% 
  head(10) %>% 
  ggplot() +
  aes(x = name, y = fires_density) +
  geom_col(fill = "#20854EFF") +
  coord_flip() +
  ylim(0, 0.208) +
  scale_x_discrete(position = "top") +
  labs(x = NULL, y = "Density of detected fires", caption = "itsprettydata.com\nData source: VIIRS I-Band 375m  |  WDPA  |  landmarkmap.org") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(family = 'ubuntu', 
                              color = 'grey10', 
                              face = 'bold',
                              size = 32, 
                              vjust = 1,
                              hjust = 0),
    plot.subtitle = element_text(size = 18, 
                                 family = "mono",
                                 color = "grey30"),
    plot.caption = element_text(color = "grey40",
                                family = 'ubuntu', 
                                size = 18, 
                                vjust = 1,
                                hjust = 0),
    axis.text.y = element_text(size = c(24, 24, 24, 24, 21,
                                        24, 24, 24, 24, 24
                                        ), family = "ubuntu", color = "grey10"),
    axis.text.x = element_text(size = 18, family = "ubuntu", color = "grey20"),
    axis.title.x = element_text(size = 22, family = "ubuntu", color = "grey20"),
    axis.ticks.y = element_line(size = 2)
  ) +
    NULL

# p_10pa
p_bars <- (p_10ind / p_10pa)
p_bars

ggsave("Output/Figures/top10_plot_rev.png", p_bars,
       dpi = 300, width = 18, height = 12
       )
# "/home/mirza/Projects/prettydata/content/post/amazon/"
ggsave(
  # "Output/Figures/top10_plot_rev.png",
       "/home/mirza/Projects/prettydata/content/post/03_amazon/top10_plot_rev.png",
       p_bars,
       dpi = 300, width = 18, height = 12
       )


# ggsave("Output/Figures/top_10_map_simpl.png", map_paind, 
#        dpi = 200, width = 14, height = 10
#        )

legend_plot <- iris %>% 
  mutate(
    id = rep(1:2, 75),
    set = rep(c("  Indigenous Territories", "  Protected Areas"), 75)
    ) %>% 
  ggplot() +
  aes(x = id, fill = as.factor(set)) +
  geom_histogram() +
  scale_fill_manual(values = c("#E18727FF", "#20854EFF")) +
  theme(
    legend.position = "right",
    legend.title = element_blank(),
    # legend.key.size = unit(1, "cm"),
    # legend.text = element_text()
    legend.key.size = unit(1.5, "cm"),
    legend.text = element_text(size = 26, family = "ubuntu", 
                               # face = "bold",
                               color = "grey10")
  )

# ggdraw(get_legend(legend_plot))

ggsave("Output/Figures/top10_legend.png", get_legend(legend_plot),
       dpi = 200, width = 6, height = 2
       )

p_bars <- (p_10ind / p_10pa)



```


# Make map

```{r}
####################################################################
####################################################################
####################################################################
####################### Create map
####################################################################


#### River data

amazon_network <- "amazon_basin.gpkg" %>%
  st_read() %>%
  mutate(
    num = c(1.5, 1)
    
      # num = c(2, 1)
  )

## PA & ind data
top_10_ind_terr <- burned_ind_areas %>% 
  mutate(
    name = fct_reorder(name, -order_density) 
  ) %>% 
  head(10) %>% 
  dplyr::select(name, order_density)

top_10_pa_areas <- burned_pa_areas %>% 
  mutate(
    name = fct_reorder(name, -order_density) 
  ) %>% 
  head(10) %>% 
  transmute(name = as.character(name), order_density)

m_10pa <-
  pa_non_ind %>% 
  inner_join(top_10_pa_areas, by = c("NAME" = "name")) %>% 
  filter(NAME %in% top_10_pa_areas$name) %>% 
  arrange(order_density) %>% 
  mutate(
    name_short = case_when(
      NAME == "Reserva Extrativista Jaci-Paraná" ~ "Jaci-Paraná",
      NAME == "Floresta Estadual De Rendimento Sustentado Mutum" ~ "Mutum",
      NAME == "Reserva Extrativista Rio Preto-Jacundá" ~ "Rio Preto-Jacundá",
      NAME == "Área De Proteção Ambiental Triunfo Do Xingu" ~ "Triunfo Do Xingu",
      NAME == "Floresta Estadual De Rendimento Sustentado Do Rio Madeira \"B\"" ~ "Do Rio Madeira \"B\"",
      NAME == "Floresta Nacional De Bom Futuro" ~ "De Bom Futuro",
      NAME == "Parque Estadual De Guajará-Mirim" ~ "De Guajará-Mirim",
      NAME == "Floresta Nacional Do Jamanxim" ~ "Do Jamanxim",
      NAME == "Reserva Biológica Nascentes Serra Do Cachimbo" ~ "Serra Do Cachimbo",
      NAME == "Reserva Extrativista Chico Mendes" ~ "Chico Mendes"
    )
  )

m_10ind <-
  indigenous_areas %>% 
    inner_join(top_10_ind_terr, by = "name") %>% 
  filter(name %in% top_10_ind_terr$name)

#####
# make map

samer_countries <- st_read("Data/samer_countries.gpkg") %>% 
  st_simplify()
# Create labels
samer_centroids_t10 <- samer_countries %>% 
  st_centroid() %>% 
  transmute(
    name = NAME_ENGLISH,
    coordx = st_coordinates(.)[, 1],
    coordy = st_coordinates(.)[, 2],
    coord_x = case_when(
      name == "Brazil" ~ coordx + 5,
      name == "Colombia" ~ coordx + 1.2,
      name == "Ecuador" ~ coordx + 2.2,
      name == "Guyana" ~ coordx + 0.5,
      name == "Suriname" ~ coordx - 0.2,
      name == "Bolivia" ~ coordx + 5,
      name == "Peru" ~ coordx - 1,
      name == "French Guiana" ~ coordx + 0.2,
      name == "Venezuela" ~ coordx - 1,
      TRUE ~ coordx
    ),
    coord_y = case_when(
      name == "Brazil" ~ coordy - 8,
      name == "Colombia" ~ coordy + 1,
      name == "French Guiana" ~ coordy + 0,
      name == "Peru" ~ coordy + 5.8,
      name == "Guyana" ~ coordy - 2,
      name == "Ecuador" ~ coordy + 0.5,
      name == "Suriname" ~ coordy + 0,
      name == "Bolivia" ~ coordy - 0,
      name == "Venezuela" ~ coordy + 1,
      TRUE ~ coordy
    ),
    name = ifelse(name == "French Guiana", "French\nGuiana", as.character(name))
  )
# load background raster
NE_samer_small <- raster("Data/NE_samer_small.tif")
NE_samer_small_ggg <- raster_to_gg(NE_samer_small)

ifl_resampled_raster <- raster("Data/IFL_raster_resampled.tif")
NE_amazon_forest_ggg <- raster_to_gg(ifl_resampled_raster)

#### Load roads


roads_br <- st_read("Output/Roads.gpkg")

amazon_river <- st_read("Data_raw/CD06_CAMREX_1086/data/amzmainstm_v/amzmainstm_v.shp")
amazon_river <- "Data_raw/network10/lineaire_10km.shp" %>% 
  st_read()

# amazon_river%>% tabyl(SOURCETHM)
  # mapview()

# mapview(amazon_river)


# Combine top10 layers

top_10_areas <- rbind(m_10pa %>% transmute(type = "pa", order_density, name = name_short), m_10ind %>% transmute(type = "ind", order_density, name))

#### Create all PAs and all indigenous areas layer (make it more transparent than top 10)
tic("PAs")
pa_all <-
  pa_non_ind %>% 
  left_join(top_10_pa_areas, by = c("NAME" = "name")) %>% 
  filter(is.na(order_density)) %>% 
  st_simplify()
toc()
tic("ind")
pa_all_ind <- indigenous_areas %>% 
    left_join(top_10_ind_terr, by = "name") %>% 
  filter(is.na(order_density)) %>% 
  st_simplify()
toc()
#### Create map
map_paind <- ggplot() +
  geom_tile(data = NE_samer_small_ggg, aes(x = x, y = y, fill = NE_samer_small),
            show.legend = FALSE) +
  scale_fill_gradient2(low = "grey60",
                       mid = "lightyellow1",
                       # mid = "green4",
                       high = "grey40") +
    geom_sf(data = amazon_network, size = c(1.5, 0.5), color = "blue2", alpha = 0.25) +
  # geom_tile(data = NE_amazon_forest_ggg, aes(x = x, y = y, fill = ifl_raster_resampled), alpha = 0.2, fill = "green2") +
  #### South america country borders    
  geom_sf(data = samer_countries, fill = NA,
          # linetype = "dotted",
          color = "grey20") +
  #### PAs and ind
  geom_sf(data = pa_all,
          alpha = 0.3,
          fill = "#20854EFF") +
  geom_sf(data = pa_all_ind,
          alpha = 0.3,
          fill = "#E18727FF") +
  # Main roads
  geom_sf(data = roads_br, color = "yellow3", size = 1.25) +
  # Top 10
  geom_sf(data = top_10_areas, 
          # aes(fill = type),
          alpha = 1,
          fill = c(rep("#20854EFF", 10),
                   rep("#E18727FF", 10))
  ) +
  #### Country name labels
  geom_sf_text(data = samer_centroids_t10, aes(x = coord_x, 
                                           y = coord_y, 
                                           label = name),
               size = 5,
               alpha = 1,
               color = "grey10", family = "Helvetica-Narrow") +
  #### Amazon biome outline
  geom_sf(data = amazon_biome, fill = NA, alpha = 0.1, color = "grey10",
          size = 1) +
  # scale_fill_manual(values = c("#E18727FF", "#20854EFF")) +
   #### Road labels
   geom_sf_label_repel(data = top_10_areas, aes(label = str_c(order_density, ": ", name)),
                      fill = c(rep("#20854EFF", 10),
                               rep("#E18727FF", 10)),
                      size = 6,
                      box.padding = 1.9,
                      label.padding = 0.25,
                      segment.color = "black",
                      segment.alpha = 0.8,
                      # nudge_x = -5,
                      # nudge_y = 5,
                      label.r = 0.25
  ) +
  #### Road number labels
    geom_sf_label(data = roads_br, 
                aes(label = ref),
                x = c(-58.2, -74, -48.8),
                y = c(-5.4, -6.8, -6.6),
                label.size = 1,
                label.padding = unit(0.2, "cm"),
                label.r = unit(0.25, "cm"),
                size = 6,
                fontface = "bold",
                color = "grey20",
                fill = "yellow3"
                ) +
  theme_map() +
  theme(
    panel.grid.major = element_blank(),
    legend.position = "none"
  ) +
  coord_sf(datum = NA, xlim = c(-78, -42), ylim = c(-21, 12))


map_paind

# fname <- str_glue("Output/Figures/top_10_ggrepel/top_10_map_simpl_{i_str}.png")

ggsave(
  # "Output/Figures/top_10_map_roads_labeled.png",
  "/home/mirza/Projects/prettydata/content/post/03_amazon/top_10_map_roads_labeled.png",
  map_paind, 
  dpi = 220, width = 14, height = 10
)  

```
